#!/bin/bash

#           Builder Module
# -----------------------------------
#   1. Build vepar zombie
#   2. Update vepar
#   3. Manage vepar installations
# -----------------------------------
#   Copyright (C) 2024 333revenge

# Menu & Banners

echo -e "\033[0;31m"

cat <<"EOF"

                                                                      ÇÆÅÅ6
                                                                ÅÅü ÞgÅÆÅggGÇ
                                                               {ÅGÅÆggÆÆÆÅÞgÅÅÏzÞÅ›
          ›íü6ÇÞgÆÆÆGz      —Þ                                 ÅÅgGÆÆÅgÅgÅggÆÅGÞÞÅ    —›                            Þz       üGÆÆÅÅgÞÏ›
                  íÆÆÆÆÆÆÆÆÆÆÆÆÞ                           íÅÆÆÆÆÅÞÆÆgÞÅÅÅÅÆÆÅÞ6ÞÅg   üz                          6ÆÆÆÆgÇÆÆÆÆÆÅ—
                Ç6    ›ÇíÆg     G›                        zÆgGgÅÆÆGÞÆÆÅÆÅÅÆÆÆÆÆGÇÞg66ÅÅ{                         g—   {ÆÆ Æ    {gÞ
                     {››Æ›   Ï  Ïz        z6 ÏÆÆÆÆÆÆÆÆÆÆü   ggÞÞgÆÆÆgÅÆÆÅGÅÆÆgÆÆÅgÅÆGÇ  ÇÆÆÆÆÆÆÆÆÆÅ{ 6          zz  —   üÆ Çü
                     6G—gÇÆí Æ6ü›     {Æ6ÆÆÆÆG   ÇÆÆgÆÆ— zÆÅÇgÅGÞÞGÅÆÆÆÆÆÅgÅÆÞgÆÅÆÅGGgz  ÏÆÅgÆÆz  ›ÅÆÆÆÅ ›Æ      zGgg ÏÆ{Åüg—
                    ›6gGz  Æ— ÞÆÆÇ    ÆÆg›  zÆÅ ›Å     GÆÆgÅÆÆÆÆÆÅÞÇgÆÆÅÅGÅÆÆÆÆÅGÞÞÅííÞüÏ     zÆ {ÆÅ{   GÅÆÅ    GÆÆg  Æ  ÇÅÇ
                         üÆÆÆÆÅÏÇÆÇÅÆÅ6Æí     üÆ›   6ÆÆÇÇÆÆÆgGgÆÆÆÆÅGGÅÅÅÆÆÆÅgGÞÇgÆÅí    íÏÆ    üÆí      üÆGÆÆü{gÏ ÇÆÆÆG
                        Þü  {6  ÞÏ     ÆÏ     ÇÆÆÆÇÇÆÆÆÆÆÆÆÆgÞÞÞgÆÆÆÆÆÆÆÆÆÆgÞÞÞgÆÆÅÅÆÆÆÆÆÆÇÆÇíGÆÆÆÏ      ÇÆ    ›Þg{ 6—  Gg
                               zü   zÆÆÆÇÏ› íÆ›{ÆGGÞügGÆÆÆÆÆÆGÇÇÞgÅÆÆÆÆÆÆÆÆÆÆÆÅgÞÞGÅÆÆÆÆÆÅÅüÏGÇÅÅ íÆ— {z ÇÆGÆ6›  ü{
                              z›—Þz  ÅÆÆ  íG—ÅíÏÆ6í›{Þ    —ÆÆÆgÞÇÇÞGggÅÆÆÆÆÅGÞÇÞgÆÆÆÆ6    íÇ {—ÅÆ{ÏGzÞ   gÆÆÆ  {güüz
                                 z—{GÆÆ   gÆÅ6zgÆÏ Ç íÞÆÆgÆÆÆÆÆÆÅÅÅÅÆÆ6ÏgÏgÅgÅGüzÆÅÆÆÆ6{ggg Ï— ÆÆGzÇÆÆü   ÆÆÞG —{
                                 üz ›ÆÆ      üÅ6Ggz   Ç{ÆÆÆÆÆÆü        ÞÆÏ        gÆÆÆÆÆgÇz  ›—ÆzGg{     üÆÆg  6í
                                   z—ÏÆÆü   zgGÞÇÇÅÆÆÆGÞ6í ›ÆGüÆÆ  ››  gÆ6  ›  zÆÅ{Æg  {Çzz6GÆGÞÞÇÞg›   gÆÆ  Ïí
                                       ÆÆÅÆÆÆÆÅGí›  z 6z  —üÆü ÅzÏÅ› 6Æí ÏÅÏ zÆ ÆG ÆÆí    G6 ›{—{ÆGÅÆÆÅÆÆÅ     ›
                                      íÆÆ6ÞÏÏG6ígÆ   GíÆÆÆÆÆÆÆ {ÆÆÆ—  üÆÆÆ—  ÏÆÆÅ {ÆÆ6gÆüÇí 6 íÞ6 6ÇÏüÞÞÆÆ
                                      ÇÆÆ{ ›ü  { Gí 6Ç z { üÅÅÆÏ      GÆÆÆz      ÇÆÇÆG —›ÏüÆü g6›ü  Ï{ —ÆÆ{
                                     ›ÅÆÆ   ü      íí  ÏÞÆÆ6zÏÞÆG—  ›ÅÆÅÇÆÆÇ   íÆÆíü{6ÆÆÇü  z{Ç      — 6ÆÆÞ6z
                                      6Æ{gÆg6G—    6  {    í6ÞÆÅÇÇgÆÆÆÞ   gÆÆÆGÇÞÇÆÇ{6—      G ›    ÇÞÅÞÞÆ
                                      —ÆÏ  ü    ›—6{Ï    ›6ggÏzÅzz66gÆÇ   GÆÞ66—6ÅüüGÅ{     —gügüüí Ïz  GÆ
                                       Æ—          ›—   {ÆÆÅÞGÅz›g  ÞÆg   ÆÆí zg 6ÆGüÞígGÏ›  —          Þz
                                        g             {ü6ÆÆÆgÇÏ     ÇÆÅ  ›ÆÆ—     ›ÆÆÆÆÆ{  z            Ç
                                        {           —GGgí     í   üÆÅGg  ›ÆGÅg    z    zÆÆz {          í
                                         ›     ›zÏ{           í  ÅÆ ÞÆG Ï›ggí gÞ  ——       ›6Çí
                                                            —ÅÆÅGü   Æí›g›66  {ÇÏ{gÅ›
                                                              zÆz   ›G üÆí Ç    üÆg
                                                              g     Þ  ÅÆÇ ››    —Æ
                                                            ÞÞ     —   ÆÆg  ›      ÅÅí
                                                           z          üÆÆÆ—          z
                                                         —            ÅÆÆÆü           ››
                                                                      ÆÆÆÆG
                                                                     ÏÆÆÆÆÆ
                                                                     ÏÆÆÆÆÆ
                                                                      {ÆÆÆ
                                                                       ›Þ
EOF


loading() {
    local delay=0.25
    local spin='/-\|'

    for i in {1..7}; do # Loop per 10 cicli
        local temp=${spin#?}
        printf "\033[0;m\r%s %c" "Loading tools..." "$spin"
        spin=$temp${spin%"$temp"}
        sleep $delay
    done
}


sleep 2 &
loading

echo -e "\n\033[0;36m    VEPAR BOTNET v$(cat ../VERSION)"
echo -e "├──────────────────────────────────────────────────"
echo -e "\033[0;36m│  1. \033[0;35mBuild zombie"
echo -e "\033[0;36m│  2. \033[0;35mInstall Vepar"
echo -e "\033[0;36m│  3. \033[0;35mUpdate Vepar"
echo -e "\033[0;36m│  4. \033[0;35mSetup Vepar"
echo -e "\033[0;36m│  5. \033[0;35mManages installations"
echo -e "\033[0;36m│  6. \033[0;35mCredits"
